### ISSUE TITLE
mastermost incoming webhook syntax changed

### ISSUE THREAD

**Issue by mrflos** [Schoaf/qa-mattermost-notifications#12]
Hi,

I had to adapt the `createMattermostMessageAttachment` function to make it work with modern Mattermost.

Here is what I return:  
```php
return array(
    'username' => utf8_encode($bot_name),
    'icon_url' => utf8_encode($icon_url),
    'text' => utf8_encode(
          "**".$pretext."**  \n"
          .'['.$title.']('.$title_link.') by '.'['.$author_name.']('.$author_link.')'."  \n"
          .$message
    ),
);
```

**Comment by Schoaf** [comment]
It seems you removed the whole message attachment. I don't know why you did that. I am not working with Mattermost anymore but it should definitely still support attachments. see https://docs.mattermost.com/developer/message-attachments.html

So you should find out what the problem really is. Because your change is limiting the formatting options and removes the action as well.

**Comment by mrflos** [comment]
ok, i will check this on another instance of Mattermost, maybe the one I used framateam.org, doesn't autorize message attachment.

**Comment by Schoaf** [comment]
As there where no further comments, I assume this problem has been resolved at your side.
Thanks for filing an issue.
Regards
